### ISSUE TITLE
css grid

### ISSUE THREAD

**Issue by balupton** [docpad/website#75]
this could be nifty

``` css
display: grid;
grid-gap: 10px 20px;
grid-template-rows: 100px 1fr auto;
grid-template-columns: 1fr 200px;
grid-template-areas: "header  header"
                     "content aside "
                     "footer  aside ";

@media (max-width: 600px) {
    grid-gap: 0;
    grid-template-rows: auto 1fr auto auto;
    grid-template-columns: 1fr;
    grid-template-areas: "header "
                         "content"
                         "aside  "
                         "footer ";
}
```

https://webkit.org/blog/7434/css-grid-layout-a-new-layout-module-for-the-web/
